// <auto-generated />
namespace TodoManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class FirstDatabaseCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207152306029_FirstDatabaseCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WzXLbNhC+dybvwMEpPUSwnRxSD5WMI9sZTyo7Eyq5r8iVjAl+WAD0SM/WQx+pr9AF/0VKVuzmkBsJ7H67++HbBf79+5/4/UbJ6AGtE0ZP2enkhEWoU5MJvZ6ywq9evWXv3734Lb7K1Cb61ti9Dnbkqd2U3Xufn3Pu0ntU4CZKpNY4s/KT1CgOmeFnJyd/8NNTjgTBCCuK4i+F9kJh+UO/M6NTzH0Bcm4ylK5ep52kRI1uQaHLIcUpW5jMzEHDGu3kEjyw6EIKoDwSlCsW5W/OvzpMvDV6neTgBcjFNkfaX4F0WGd9nr/50cRPzkLiHLQ2nuCMflbhrC2Jirqi4v02pFUWVtXUtyCbT7jdWaClz9bkaP32C65qv5uMRXzXjw8dW7eeTwhNX9q/PmPRbSElLCW2DBGFiTcWP6JGCx6zz+A9Wh18sUx9FHUQ4xJdakVesVUFoxMhSbHoWmww+xP12t+3AeewaVbok0VftSAFkpO3Be5J8Ehwo7GJ+sEYiaCPYMS8O5HxOZE4PQiiondYYQ03fnBmlX2CvmfpWNSBVyKdlMe9N4M2VtcBvGqBplX4gV6J55DnxHCvd+qVKKkaZ/Yqebp0VYXBU7dHwW22bSSSDTXmYJdCU6bXwjofGnYJgf9ZpkZmP8BsE6lP8LBPOr4b6/DdefSnx2Tcen3urqkcRZovK8M2i30dWzsmKUiwe3puZmSh9KG+fcx7p5v6MDsbT8ArG2QHqFwZI8R8wMOQaj7iejCNhgf3mOaHJm30VvsDjce13o5fGiMBViYsImoeRBbEl2ydR1WJIvlLzqSgejsDEo1YofML8x1pElJ/vB3cPM+4FbhzmfwVrwYRSj96CTx1MI9vBf0ANr0H+1LB5vf/NemXwv/UKT8eWcdn/cFRX6ltyrIl/SyqDMMOumdfA2Ppx7z/qoqJbbHuIMIbS2MayO9AG5sbvTINt1RSP6PGZED9HD1kxMyF9WIFqaft"
                       + "FJ0rr/hvIAsyuVJLzG70XeHzwl84h2opd14OMX88fnnX7eYc35XycT+jBEpTUAl4pz8UQmZt3td7pHMAIoikbhDKip44BLfetki3o7F6CKim7xJz1KG9FqhySWDuTifwgIdzO87hLmPxpYC1BeVqjM4/PPJ5eOW/+w9yA/FWFwwAAA=="; }
        }
    }
}
