// <auto-generated />
namespace TodoManager.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialDb : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201207181508355_InitialDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Wy3ITOxDdU8U/TM2Ku8BKAgtIjaGCk1ApcEIxhn17pu2o0GOupEnZ38aCT+IXaM37YcchsGA3I3Wf7j463dLP7z+itxspgjs0lms1DY8nR2GAKtEpV+tpmLvV81fh2zdPn0QXqdwEX2u7F96OPJWdhrfOZaeM2eQWJdiJ5InRVq/cJNGSQarZydHRa3Z8zJAgQsIKguhzrhyXWPzQ70yrBDOXg5jrFIWt1mknLlCDa5BoM0hwGi50quegYI1mUlqHwZngQJnEKFZhkL08/WIxdkardZyB4yAW2wxpfwXCYpX3afbyoakfnfjUGSilHcFp9ajSw6YoKuuCyndbn1ZRWllV14JsPuC2t0BLn4zO0LjtZ1xVfldpGLC+Hxs6Nm4dHx+avpR7cRIG17kQsBTYMEQUxk4bfI8KDThMP4FzaJT3xSL1UdRBjHO0ieFZyVYZjE6ERBUGl3yD6UdUa3fbBJzDpl6hzzD4ojhpkJycybGbYPl/ILZWWAd9p7VAUDtq7GJErD2Q8TGROh1wYqJzVn4NN25wZKV9jK5jSfJswUuNTorT3plBE6ttAVb2QN0rbE+zRHPIMiK40zzVShCXnTN7Hv++cmWJwRK7Q8BNtk0kUg115mCXQlOml9xYdw4OluD5n6VyZPYAZutIXYKHbdLyXVv779ajPz4m497rsndJBUkSfVEbNnnsatnKMU5AgNnRdDMtcqn2Ne593r126sL0Nn4Dr2iRHlCxMkaI2ICHIdlsxPZgHA2P7j7VD02a6I36ByqPKsUdvjdGEixNwoCoueOpl1+8tQ7lxBtM4v/FTHCqtzUg2fAVWrfQ35BGIXXIq8HV84hrgVmbin/xbuC+9IO3wL1j9UHXgroDk9yCeSZh89+fjPold391zI9n1uFhv3fWl2KbhumSfhZlhn4H7aPvgbHyI9Z9V0VENl+3EP6VpTDx3Legtc2VWumaWyqpm1FtMqB+jg5SYubMOL6C"
                       + "xNF2gtYWV/xXEDmZXMglplfqJndZ7s6sRbkUvZdDxO6PX1x2/Zyjm0I99m+UQGlyKgFv1Luci7TJ+3KHdPZAeJFU/UFZ0ROH4NbbBul6NFX3AVX0nWOGynfXAmUmCMzeqBjucH9uhznsMxadc1gbkLbCaP39M5/5d/6bX2TKd4kZDAAA"; }
        }
    }
}
